name: Xcode Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - generic/platform=macOS
          - generic/platform=macOS,variant=Mac Catalyst
          - generic/platform=iOS
          - generic/platform=tvOS
          - generic/platform=watchOS
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild \
          -scheme UIImageColors-Package \
          -destination '${{ matrix.destination }}'
      - name: Test
        run: |
          xcodebuild \
          -scheme UIImageColors-Package \
          -destination '${{ matrix.destination }}' \
          test
